# Generated by Django 5.1.4 on 2025-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados unidos'), ('BRA', 'Brasil'), ('AUS', 'Australia'), ('ENG', 'Inglaterra')], max_length=100, null=True),
        ),
    ]
