# Generated by Django 5.1.4 on 2025-01-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
