# Generated by Django 5.1.4 on 2025-01-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_actor_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
