# Generated by Django 5.1.4 on 2025-01-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_alter_actor_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
    ]
