# Generated by Django 5.1.4 on 2025-01-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_genre_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
