# Generated by Django 5.1.4 on 2025-01-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='subtitle',
        ),
    ]
