# Generated by Django 5.1.4 on 2025-01-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
