# Generated by Django 5.1.4 on 2025-01-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
